---
- name: Deploy site dev.manngroup.ru
  hosts: all
  tasks:
    - name: Получение файлов магазина из архива
      ansible.builtin.get_url:
        url: "ftp://{{ ftp_user }}:{{ ftp_pass }}@{{ ftp_address }}/{{ name_file_dump_shop }}"
        dest: "{{ path_to_dir }}"
        mode: "0755"

    - name: Проверка существования файлов магазина
      ansible.builtin.stat:
        path: "{{ path_to_dir }}/{{ name_work_dir }}"
      register: check_dir_name

    - name: Подготовка к запуску нового магазина
      block:
        - name: Остановка магазина
          community.docker.docker_compose:
            project_src: "{{ path_to_dir }}/{{ name_work_dir }}"
            state: absent

        - name: Перемещение файлов магазина в новую директорию
          ansible.builtin.copy:
            src: "{{ path_to_dir }}/{{ name_work_dir }}/"
            dest: "{{ path_to_dir }}/{{ name_work_dir }}_{{ ansible_date_time.date }}"
            remote_src: true
            mode: "0755"

        - name: Удаление файлов старого магазина
          ansible.builtin.file:
            path: "{{ path_to_dir }}/{{ name_work_dir }}"
            state: absent

      when: check_dir_name.stat.exists

    - name: Распаковка файлов нового магазина
      ansible.builtin.unarchive:
        src: "{{ path_to_dir }}/{{ name_file_dump_shop }}"
        dest: "{{ path_to_dir }}"
        remote_src: true

    - name: Замена docker-compose файла
      vars:
        content_docker_file: "{{ lookup('file', './files/docker-compose.yml') }}"
      ansible.builtin.copy:
        content: "{{ content_docker_file }}"
        dest: "{{ path_to_dir }}/{{ name_work_dir }}/docker-compose.yml"
        mode: "0644"

    - name: Смена прав у каталогов
      ansible.builtin.command: find app/www -type d -exec chmod 0777 {} \;
      args:
        chdir: "{{ path_to_dir }}/{{ name_work_dir }}/"
      changed_when: true

    - name: Смена прав у файлов
      ansible.builtin.command: find app/www -type f -exec chmod 0666 {} \;
      args:
        chdir: "{{ path_to_dir }}/{{ name_work_dir }}/"
      changed_when: true

    - name: Запуск контейнеров
      community.docker.docker_compose:
        project_src: "{{ path_to_dir }}/{{ name_work_dir }}"
        state: present
